version: '3.8'

services:
  app_countries_bot:
    container_name: app_countries_bot
    env_file:
      - .env
    environment:
      REDIS_URL: 'redis://app_redis'
      DB_HOST: 'app_db'
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "
        echo 'Starting project...' &&
        python manage.py migrate
        python manage.py initadmin
        python main.py & python manage.py runserver 0.0.0.0:8000
      "
    networks:
      - prod_network
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      app_db:
        condition: service_healthy
      app_redis:
        condition: service_healthy
      app_rabbitmq:
        condition: service_healthy

  app_db:
    container_name: app_db
    image: postgres:15.1-alpine
    volumes:
      - psql:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - '5432:5432'
    networks:
      - prod_network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 10s
      timeout: 5s
      retries: 10

  app_redis:
    container_name: app_redis
    image: redis:latest
    env_file:
      - .env
    expose:
      - 6379
    ports:
      - '6379:6379'
    networks:
      - prod_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  app_rabbitmq:
    container_name: app_rabbitmq
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    env_file:
      - .env
    expose:
      - 5672
      - 15672
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - prod_network
    healthcheck:
      test:  ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  prod_network:
    name: prod_network
    driver: bridge

volumes:
  psql:
