# Generated by Django 4.1.7 on 2023-03-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('geoname_id', models.PositiveIntegerField(
                    primary_key=True, serialize=False, verbose_name='geoname id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('longitude', models.DecimalField(
                    decimal_places=4, max_digits=7, verbose_name='longitude')),
                ('latitude', models.DecimalField(
                    decimal_places=4, max_digits=7, verbose_name='latitude')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso_code', models.CharField(max_length=50,
                 primary_key=True, serialize=False, verbose_name='ISO code')),
                ('name', models.CharField(max_length=50,
                 unique=True, verbose_name='name')),
                ('population', models.PositiveIntegerField(
                    verbose_name='population')),
                ('area_size', models.PositiveIntegerField(verbose_name='area size')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='updated at')),
                ('capital', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                 related_name='country_capital', to='countries_app.city', verbose_name='capital')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50,
                 unique=True, verbose_name='name')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='updated at')),
                ('country', models.ManyToManyField(
                    related_name='languages', to='countries_app.country')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('iso_code', models.CharField(max_length=30,
                 primary_key=True, serialize=False, verbose_name='ISO code')),
                ('name', models.CharField(max_length=30,
                 unique=True, verbose_name='name')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='updated at')),
                ('country', models.ManyToManyField(
                    related_name='currencies', to='countries_app.country')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='cities', to='countries_app.country', verbose_name='country'),
        ),
    ]
