# Generated by Django 4.1.7 on 2023-03-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_app', '0002_remove_city_geoname_id_city_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 to='countries_app.city', verbose_name='city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 to='countries_app.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'capital',
                'verbose_name_plural': 'capitals',
            },
        ),
    ]
