# Generated by Django 4.1.7 on 2023-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_app', '0003_remove_country_capital_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_capital',
            field=models.BooleanField(),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Capital',
        ),
    ]
